### ISSUE TITLE
isNotEmpty() passes for missing node

### ISSUE THREAD

**Issue by lmartelli** [webcompere/model-assert#53]
The following test passes (unfortunately)
```
@Test
void isNotEmptyOnMissingIsFalse() {
    assertJson("{}").at("/prop").isNotEmpty();
}
```
Because isNotEmpty() is the negation of isEmpty() which considers missing nodes as not empty.
This could be fixed by modifying isEmpty() to return true for missing nodes (maybe also for `null`?), but that would break compatibility.
Or writing a proper IsNotEmpty condition.

What's your option on this @ashleyfrieze ?

**Comment by ashleyfrieze** [comment]
Release 1.1.0 resolves this issue.
